apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-health-check-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Michigety/flask_kustomize.git
    targetRevision: main
    path: overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
