name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image digest
      run: echo "${{ steps.meta.outputs.tags }}" > image_tags.txt

    - name: Upload image tags
      uses: actions/upload-artifact@v4
      with:
        name: image-tags
        path: image_tags.txt

  update-kustomize:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download image tags
      uses: actions/download-artifact@v4
      with:
        name: image-tags

    - name: Get image tag
      id: image-tag
      run: |
        IMAGE_TAG=$(cat image_tags.txt | head -n 1)
        echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
        echo "Using image tag: ${IMAGE_TAG}"

    - name: Checkout deployment repository
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.DEPLOYMENT_REPO }}
        token: ${{ secrets.DEPLOYMENT_TOKEN }}
        path: deployment

    - name: Update Kustomize image
      run: |
        cd deployment/k8s/base
        kustomize edit set image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.image_tag }}

    - name: Configure Git
      run: |
        cd deployment
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        cd deployment
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update image to ${{ steps.image-tag.outputs.image_tag }}")
        git push origin main
